import type {
  User,
  Project,
  Notification,
  Blueprint,
  GenerationStage,
} from "@/types";

export const sampleUser: User = {
  id: "usr_01",
  name: "Alex Chen",
  email: "alex@productstudio.ai",
  plan: "pro",
  createdAt: "2025-09-15T10:00:00Z",
};

export const sampleBlueprint: Blueprint = {
  id: "bp_01",
  projectId: "proj_01",
  overview: {
    summary:
      "A comprehensive marketplace platform connecting independent artisans with conscious consumers. The platform emphasizes curation, storytelling, and sustainable commerce.",
    vision:
      "To become the definitive digital destination where craftsmanship meets commerce, enabling artisans worldwide to build sustainable businesses while giving consumers access to unique, handcrafted products.",
    objectives: [
      "Enable artisans to create and manage digital storefronts",
      "Provide consumers with curated discovery experiences",
      "Facilitate secure transactions with escrow protection",
      "Build community through artisan stories and workshops",
      "Implement intelligent recommendation engine",
    ],
    targetUsers: [
      "Independent artisans and craftspeople",
      "Conscious consumers seeking unique products",
      "Craft workshop organizers",
      "Wholesale buyers and boutique retailers",
    ],
    techStack: [
      { category: "Frontend", name: "Next.js 15", reason: "Server-side rendering for SEO-critical marketplace pages" },
      { category: "Backend", name: "FastAPI", reason: "High-performance async API for real-time features" },
      { category: "Database", name: "PostgreSQL", reason: "Complex relational data with full-text search" },
      { category: "Search", name: "Elasticsearch", reason: "Advanced product discovery and filtering" },
      { category: "Storage", name: "AWS S3", reason: "Scalable media storage for product images" },
      { category: "Payments", name: "Stripe Connect", reason: "Multi-party marketplace payments" },
      { category: "Cache", name: "Redis", reason: "Session management and real-time features" },
      { category: "CDN", name: "Cloudflare", reason: "Global content delivery and edge caching" },
    ],
    estimatedTimeline: "16 weeks",
    complexity: "high",
  },
  requirements: [
    {
      id: "req_01",
      category: "functional",
      title: "Artisan Storefront Management",
      description: "Artisans must be able to create, customize, and manage their digital storefronts including branding, product listings, and order fulfillment workflows.",
      priority: "critical",
      status: "approved",
    },
    {
      id: "req_02",
      category: "functional",
      title: "Product Discovery Engine",
      description: "Consumers should discover products through intelligent search, curated collections, category browsing, and personalized recommendations.",
      priority: "critical",
      status: "approved",
    },
    {
      id: "req_03",
      category: "functional",
      title: "Secure Payment Processing",
      description: "Support multi-party payments with escrow, automated payouts to artisans, and buyer protection policies.",
      priority: "critical",
      status: "approved",
    },
    {
      id: "req_04",
      category: "non-functional",
      title: "Performance Requirements",
      description: "Page load times under 2 seconds, search results within 200ms, support for 10,000 concurrent users.",
      priority: "high",
      status: "approved",
    },
    {
      id: "req_05",
      category: "technical",
      title: "API Architecture",
      description: "RESTful API with OpenAPI documentation, rate limiting, versioning, and webhook support for third-party integrations.",
      priority: "high",
      status: "approved",
    },
    {
      id: "req_06",
      category: "business",
      title: "Revenue Model",
      description: "Commission-based revenue with tiered pricing, featured listings, and premium artisan subscription plans.",
      priority: "high",
      status: "approved",
    },
    {
      id: "req_07",
      category: "functional",
      title: "Review and Rating System",
      description: "Verified purchase reviews with photo uploads, artisan response capabilities, and trust scoring.",
      priority: "medium",
      status: "approved",
    },
    {
      id: "req_08",
      category: "non-functional",
      title: "Accessibility Compliance",
      description: "WCAG 2.1 AA compliance across all consumer-facing pages with screen reader optimization.",
      priority: "high",
      status: "approved",
    },
  ],
  userStories: [
    {
      id: "us_01",
      epic: "Artisan Onboarding",
      title: "As an artisan, I want to create my storefront",
      description: "As an artisan, I want to create a personalized storefront so that I can showcase my craft and brand identity to potential customers.",
      acceptanceCriteria: [
        "Artisan can upload a logo and banner image",
        "Artisan can write a bio and craft story",
        "Storefront has a unique URL slug",
        "Preview is available before publishing",
      ],
      priority: "critical",
      points: 8,
    },
    {
      id: "us_02",
      epic: "Product Management",
      title: "As an artisan, I want to list my products",
      description: "As an artisan, I want to create detailed product listings with multiple images, variants, and pricing so buyers can make informed decisions.",
      acceptanceCriteria: [
        "Upload up to 10 images per product",
        "Define size, color, and material variants",
        "Set pricing with optional sale pricing",
        "Add tags for discoverability",
        "Save as draft or publish immediately",
      ],
      priority: "critical",
      points: 13,
    },
    {
      id: "us_03",
      epic: "Discovery",
      title: "As a consumer, I want to search for products",
      description: "As a consumer, I want to search and filter products by category, price, material, and artisan location so I can find exactly what I need.",
      acceptanceCriteria: [
        "Full-text search across product titles and descriptions",
        "Filter by category, price range, material, and location",
        "Sort by relevance, price, newest, and popularity",
        "Search suggestions and autocomplete",
      ],
      priority: "critical",
      points: 8,
    },
    {
      id: "us_04",
      epic: "Checkout",
      title: "As a consumer, I want to purchase products securely",
      description: "As a consumer, I want a streamlined checkout experience with multiple payment options and order tracking.",
      acceptanceCriteria: [
        "Guest checkout available",
        "Support credit cards and digital wallets",
        "Order confirmation with estimated delivery",
        "Real-time order status tracking",
      ],
      priority: "critical",
      points: 13,
    },
    {
      id: "us_05",
      epic: "Community",
      title: "As a consumer, I want to follow artisans",
      description: "As a consumer, I want to follow my favorite artisans and receive updates about new products and workshops.",
      acceptanceCriteria: [
        "Follow button on artisan profiles",
        "Notification feed for followed artisans",
        "Email digest of new products",
        "Following count visible on profile",
      ],
      priority: "medium",
      points: 5,
    },
    {
      id: "us_06",
      epic: "Analytics",
      title: "As an artisan, I want to view my sales analytics",
      description: "As an artisan, I want to see detailed analytics about my storefront performance including views, conversions, and revenue.",
      acceptanceCriteria: [
        "Dashboard with key metrics overview",
        "Revenue charts with date range filtering",
        "Product performance comparison",
        "Customer demographics breakdown",
      ],
      priority: "high",
      points: 8,
    },
  ],
  database: {
    tables: [
      {
        name: "users",
        description: "Core user accounts for both artisans and consumers",
        columns: [
          { name: "id", type: "UUID", nullable: false, primaryKey: true, description: "Primary key" },
          { name: "email", type: "VARCHAR(255)", nullable: false, primaryKey: false, description: "User email address" },
          { name: "name", type: "VARCHAR(100)", nullable: false, primaryKey: false, description: "Display name" },
          { name: "role", type: "ENUM", nullable: false, primaryKey: false, description: "artisan, consumer, admin" },
          { name: "avatar_url", type: "TEXT", nullable: true, primaryKey: false, description: "Profile photo URL" },
          { name: "created_at", type: "TIMESTAMP", nullable: false, primaryKey: false, description: "Account creation time" },
          { name: "updated_at", type: "TIMESTAMP", nullable: false, primaryKey: false, description: "Last update time" },
        ],
      },
      {
        name: "storefronts",
        description: "Artisan digital storefronts",
        columns: [
          { name: "id", type: "UUID", nullable: false, primaryKey: true, description: "Primary key" },
          { name: "artisan_id", type: "UUID", nullable: false, primaryKey: false, foreignKey: "users.id", description: "Owner reference" },
          { name: "name", type: "VARCHAR(100)", nullable: false, primaryKey: false, description: "Storefront name" },
          { name: "slug", type: "VARCHAR(100)", nullable: false, primaryKey: false, description: "URL-friendly identifier" },
          { name: "description", type: "TEXT", nullable: true, primaryKey: false, description: "Storefront description" },
          { name: "logo_url", type: "TEXT", nullable: true, primaryKey: false, description: "Logo image URL" },
          { name: "banner_url", type: "TEXT", nullable: true, primaryKey: false, description: "Banner image URL" },
          { name: "is_published", type: "BOOLEAN", nullable: false, primaryKey: false, description: "Publication status" },
        ],
      },
      {
        name: "products",
        description: "Product listings by artisans",
        columns: [
          { name: "id", type: "UUID", nullable: false, primaryKey: true, description: "Primary key" },
          { name: "storefront_id", type: "UUID", nullable: false, primaryKey: false, foreignKey: "storefronts.id", description: "Parent storefront" },
          { name: "title", type: "VARCHAR(200)", nullable: false, primaryKey: false, description: "Product title" },
          { name: "description", type: "TEXT", nullable: false, primaryKey: false, description: "Detailed description" },
          { name: "price", type: "DECIMAL(10,2)", nullable: false, primaryKey: false, description: "Base price" },
          { name: "category_id", type: "UUID", nullable: false, primaryKey: false, foreignKey: "categories.id", description: "Product category" },
          { name: "status", type: "ENUM", nullable: false, primaryKey: false, description: "draft, active, sold_out, archived" },
          { name: "created_at", type: "TIMESTAMP", nullable: false, primaryKey: false, description: "Listing creation time" },
        ],
      },
      {
        name: "orders",
        description: "Purchase orders",
        columns: [
          { name: "id", type: "UUID", nullable: false, primaryKey: true, description: "Primary key" },
          { name: "buyer_id", type: "UUID", nullable: false, primaryKey: false, foreignKey: "users.id", description: "Buyer reference" },
          { name: "total_amount", type: "DECIMAL(10,2)", nullable: false, primaryKey: false, description: "Order total" },
          { name: "status", type: "ENUM", nullable: false, primaryKey: false, description: "pending, paid, shipped, delivered, refunded" },
          { name: "shipping_address", type: "JSONB", nullable: false, primaryKey: false, description: "Delivery address" },
          { name: "created_at", type: "TIMESTAMP", nullable: false, primaryKey: false, description: "Order placement time" },
        ],
      },
      {
        name: "reviews",
        description: "Product reviews from verified buyers",
        columns: [
          { name: "id", type: "UUID", nullable: false, primaryKey: true, description: "Primary key" },
          { name: "product_id", type: "UUID", nullable: false, primaryKey: false, foreignKey: "products.id", description: "Reviewed product" },
          { name: "user_id", type: "UUID", nullable: false, primaryKey: false, foreignKey: "users.id", description: "Review author" },
          { name: "rating", type: "INTEGER", nullable: false, primaryKey: false, description: "1-5 star rating" },
          { name: "content", type: "TEXT", nullable: true, primaryKey: false, description: "Review text" },
          { name: "created_at", type: "TIMESTAMP", nullable: false, primaryKey: false, description: "Review submission time" },
        ],
      },
      {
        name: "categories",
        description: "Product category taxonomy",
        columns: [
          { name: "id", type: "UUID", nullable: false, primaryKey: true, description: "Primary key" },
          { name: "name", type: "VARCHAR(100)", nullable: false, primaryKey: false, description: "Category name" },
          { name: "slug", type: "VARCHAR(100)", nullable: false, primaryKey: false, description: "URL-friendly identifier" },
          { name: "parent_id", type: "UUID", nullable: true, primaryKey: false, foreignKey: "categories.id", description: "Parent category for hierarchy" },
        ],
      },
    ],
    relationships: [
      { from: "users", to: "storefronts", type: "one-to-many" },
      { from: "storefronts", to: "products", type: "one-to-many" },
      { from: "users", to: "orders", type: "one-to-many" },
      { from: "products", to: "reviews", type: "one-to-many" },
      { from: "users", to: "reviews", type: "one-to-many" },
      { from: "categories", to: "products", type: "one-to-many" },
    ],
  },
  api: [
    { id: "api_01", method: "POST", path: "/api/v1/auth/register", summary: "Register new user", description: "Create a new user account with email verification", auth: false, category: "Authentication", requestBody: '{ email, password, name, role }', responseBody: '{ user, token }' },
    { id: "api_02", method: "POST", path: "/api/v1/auth/login", summary: "User login", description: "Authenticate user and return JWT token pair", auth: false, category: "Authentication", requestBody: '{ email, password }', responseBody: '{ user, accessToken, refreshToken }' },
    { id: "api_03", method: "GET", path: "/api/v1/products", summary: "List products", description: "Retrieve paginated product listings with search and filters", auth: false, category: "Products", responseBody: '{ products[], pagination }' },
    { id: "api_04", method: "POST", path: "/api/v1/products", summary: "Create product", description: "Create a new product listing for an artisan storefront", auth: true, category: "Products", requestBody: '{ title, description, price, images[], category_id }', responseBody: '{ product }' },
    { id: "api_05", method: "GET", path: "/api/v1/products/:id", summary: "Get product details", description: "Retrieve full product details including variants and reviews", auth: false, category: "Products", responseBody: '{ product, variants[], reviews[] }' },
    { id: "api_06", method: "GET", path: "/api/v1/storefronts/:slug", summary: "Get storefront", description: "Retrieve artisan storefront by URL slug", auth: false, category: "Storefronts", responseBody: '{ storefront, products[], stats }' },
    { id: "api_07", method: "POST", path: "/api/v1/orders", summary: "Create order", description: "Place a new order with payment processing", auth: true, category: "Orders", requestBody: '{ items[], shipping_address, payment_method }', responseBody: '{ order, payment_intent }' },
    { id: "api_08", method: "GET", path: "/api/v1/orders/:id", summary: "Get order details", description: "Retrieve order details with tracking information", auth: true, category: "Orders", responseBody: '{ order, items[], tracking }' },
    { id: "api_09", method: "POST", path: "/api/v1/reviews", summary: "Create review", description: "Submit a product review for a verified purchase", auth: true, category: "Reviews", requestBody: '{ product_id, rating, content, images[] }', responseBody: '{ review }' },
    { id: "api_10", method: "GET", path: "/api/v1/analytics/dashboard", summary: "Get analytics dashboard", description: "Retrieve artisan dashboard analytics with configurable date ranges", auth: true, category: "Analytics", responseBody: '{ revenue, orders, views, topProducts[] }' },
  ],
  architecture: [
    {
      name: "Presentation Layer",
      description: "Client-facing web application with server-side rendering",
      components: [
        { name: "Next.js Application", description: "Server-rendered React application with app router", technology: "Next.js 15", connections: ["API Gateway"] },
        { name: "Design System", description: "Shared component library with consistent styling", technology: "Tailwind CSS", connections: ["Next.js Application"] },
        { name: "State Management", description: "Client-side state with server state synchronization", technology: "Zustand + React Query", connections: ["Next.js Application"] },
      ],
    },
    {
      name: "API Layer",
      description: "RESTful API with authentication and rate limiting",
      components: [
        { name: "API Gateway", description: "Request routing, rate limiting, and authentication", technology: "FastAPI", connections: ["Business Logic Layer", "Authentication Service"] },
        { name: "Authentication Service", description: "JWT-based authentication with OAuth2 support", technology: "Supabase Auth", connections: ["User Database"] },
        { name: "WebSocket Server", description: "Real-time notifications and live updates", technology: "FastAPI WebSockets", connections: ["Redis Cache"] },
      ],
    },
    {
      name: "Business Logic Layer",
      description: "Core domain services and business rules",
      components: [
        { name: "Product Service", description: "Product CRUD, search indexing, and inventory management", technology: "Python", connections: ["PostgreSQL", "Search Engine"] },
        { name: "Order Service", description: "Order processing, payment handling, and fulfillment", technology: "Python", connections: ["PostgreSQL", "Payment Gateway"] },
        { name: "Notification Service", description: "Multi-channel notification delivery", technology: "Celery", connections: ["Redis Cache", "Email Service"] },
      ],
    },
    {
      name: "Data Layer",
      description: "Persistent storage and caching infrastructure",
      components: [
        { name: "PostgreSQL", description: "Primary relational database for structured data", technology: "PostgreSQL 16", connections: [] },
        { name: "Redis Cache", description: "Session storage, caching, and message brokering", technology: "Redis 7", connections: [] },
        { name: "Search Engine", description: "Full-text search and product discovery", technology: "Elasticsearch", connections: ["PostgreSQL"] },
        { name: "Object Storage", description: "Media files, product images, and documents", technology: "AWS S3", connections: [] },
      ],
    },
  ],
  roadmap: [
    {
      id: "phase_01",
      name: "Foundation",
      duration: "4 weeks",
      description: "Core infrastructure, authentication, and basic data models",
      milestones: [
        { title: "Project Setup", description: "Repository, CI/CD, and development environment", tasks: ["Initialize monorepo", "Configure CI/CD pipeline", "Set up staging environment", "Configure linting and formatting"], estimatedDays: 3 },
        { title: "Authentication System", description: "User registration, login, and session management", tasks: ["Implement Supabase Auth integration", "Build registration flow", "Create login with OAuth", "Set up role-based access control"], estimatedDays: 5 },
        { title: "Database Schema", description: "Core database tables and migrations", tasks: ["Design and create schema", "Write migration scripts", "Seed development data", "Set up database backups"], estimatedDays: 4 },
        { title: "API Foundation", description: "Base API structure with middleware", tasks: ["Configure FastAPI application", "Implement error handling", "Set up API documentation", "Create health check endpoints"], estimatedDays: 3 },
      ],
      deliverables: ["Working development environment", "Authentication flow", "Database with initial schema", "API documentation"],
    },
    {
      id: "phase_02",
      name: "Core Features",
      duration: "5 weeks",
      description: "Storefront management, product listings, and discovery",
      milestones: [
        { title: "Storefront Builder", description: "Artisan storefront creation and management", tasks: ["Build storefront editor", "Implement image upload", "Create public storefront page", "Add customization options"], estimatedDays: 8 },
        { title: "Product Management", description: "Product listing CRUD and media handling", tasks: ["Create product listing form", "Implement variant management", "Build image gallery upload", "Add inventory tracking"], estimatedDays: 7 },
        { title: "Search and Discovery", description: "Product search with filters and recommendations", tasks: ["Integrate Elasticsearch", "Build search UI components", "Implement category browsing", "Create filter system"], estimatedDays: 7 },
      ],
      deliverables: ["Functional storefronts", "Product listing system", "Search and discovery engine"],
    },
    {
      id: "phase_03",
      name: "Commerce",
      duration: "4 weeks",
      description: "Shopping cart, checkout, payments, and order management",
      milestones: [
        { title: "Shopping Cart", description: "Cart management with persistent storage", tasks: ["Build cart data model", "Create cart UI components", "Implement cart persistence", "Add quantity management"], estimatedDays: 5 },
        { title: "Checkout Flow", description: "Multi-step checkout with address and payment", tasks: ["Design checkout flow", "Integrate Stripe Connect", "Build address management", "Create order confirmation"], estimatedDays: 8 },
        { title: "Order Management", description: "Order tracking and fulfillment", tasks: ["Build order dashboard", "Implement status updates", "Create notification system", "Add shipping integration"], estimatedDays: 7 },
      ],
      deliverables: ["Shopping cart system", "Secure checkout flow", "Order management dashboard"],
    },
    {
      id: "phase_04",
      name: "Polish and Launch",
      duration: "3 weeks",
      description: "Performance optimization, testing, and production deployment",
      milestones: [
        { title: "Testing Suite", description: "Comprehensive testing across all features", tasks: ["Write unit tests", "Create integration tests", "Perform load testing", "Conduct security audit"], estimatedDays: 7 },
        { title: "Performance Optimization", description: "Speed and reliability improvements", tasks: ["Optimize database queries", "Implement CDN caching", "Add image optimization", "Configure monitoring"], estimatedDays: 5 },
        { title: "Production Launch", description: "Deployment and go-live preparation", tasks: ["Configure production environment", "Set up DNS and SSL", "Create runbooks", "Deploy and monitor"], estimatedDays: 5 },
      ],
      deliverables: ["Test coverage report", "Performance benchmarks", "Production deployment", "Monitoring dashboards"],
    },
  ],
  generatedAt: "2025-12-10T14:30:00Z",
};

export const sampleProjects: Project[] = [
  {
    id: "proj_01",
    name: "Artisan Marketplace",
    description: "A curated marketplace connecting independent artisans with conscious consumers seeking unique, handcrafted products.",
    status: "completed",
    createdAt: "2025-12-10T14:00:00Z",
    updatedAt: "2025-12-10T14:30:00Z",
    blueprint: sampleBlueprint,
    input: {
      productName: "Artisan Marketplace",
      description: "A curated marketplace connecting independent artisans with conscious consumers",
      targetAudience: "Independent artisans, conscious consumers, craft enthusiasts",
      coreFeatures: ["Storefront builder", "Product discovery", "Secure payments", "Community features"],
      constraints: ["Must support international shipping", "GDPR compliance required"],
    },
    version: 3,
  },
  {
    id: "proj_02",
    name: "Clinical Trial Manager",
    description: "Enterprise platform for managing clinical trials with real-time patient monitoring, protocol management, and regulatory compliance tracking.",
    status: "completed",
    createdAt: "2025-12-08T09:00:00Z",
    updatedAt: "2025-12-08T15:20:00Z",
    version: 2,
    tags: ["healthcare", "enterprise"],
  },
  {
    id: "proj_03",
    name: "Sustainably",
    description: "Carbon footprint tracking application for businesses with supply chain analysis, reporting dashboards, and offset marketplace integration.",
    status: "generating",
    createdAt: "2025-12-12T11:00:00Z",
    updatedAt: "2025-12-12T11:05:00Z",
    version: 1,
    tags: ["sustainability", "analytics"],
  },
  {
    id: "proj_04",
    name: "Harmony Learning",
    description: "Adaptive learning platform that personalizes educational content using cognitive science principles and spaced repetition algorithms.",
    status: "draft",
    createdAt: "2025-12-11T16:00:00Z",
    updatedAt: "2025-12-11T16:00:00Z",
    version: 1,
    tags: ["education", "ai"],
  },
  {
    id: "proj_05",
    name: "Fleet Command",
    description: "Real-time fleet management system with route optimization, predictive maintenance alerts, and driver performance analytics.",
    status: "completed",
    createdAt: "2025-11-28T08:00:00Z",
    updatedAt: "2025-12-01T12:00:00Z",
    version: 4,
    tags: ["logistics", "iot"],
  },
  {
    id: "proj_06",
    name: "Memo",
    description: "Secure internal communications platform with end-to-end encryption, threaded conversations, and enterprise compliance features.",
    status: "archived",
    createdAt: "2025-10-15T10:00:00Z",
    updatedAt: "2025-11-20T14:00:00Z",
    version: 2,
    tags: ["communication", "security"],
  },
];

export const sampleNotifications: Notification[] = [
  {
    id: "notif_01",
    title: "Blueprint Generated",
    message: "Artisan Marketplace blueprint has been successfully generated with 8 requirements and 6 user stories.",
    type: "success",
    read: false,
    createdAt: "2025-12-10T14:30:00Z",
  },
  {
    id: "notif_02",
    title: "Generation In Progress",
    message: "Sustainably is currently being analyzed. Estimated completion in 3 minutes.",
    type: "info",
    read: false,
    createdAt: "2025-12-12T11:05:00Z",
  },
  {
    id: "notif_03",
    title: "Plan Upgraded",
    message: "Your workspace has been upgraded to Pro. You now have access to unlimited blueprints and priority generation.",
    type: "success",
    read: true,
    createdAt: "2025-12-09T10:00:00Z",
  },
];

export const defaultGenerationStages: GenerationStage[] = [
  { id: "stage_01", name: "Requirement Analysis", description: "Analyzing product requirements and constraints", status: "pending", progress: 0 },
  { id: "stage_02", name: "Feature Extraction", description: "Identifying and structuring core features", status: "pending", progress: 0 },
  { id: "stage_03", name: "UI Architecture", description: "Designing user interface structure and flows", status: "pending", progress: 0 },
  { id: "stage_04", name: "Database Design", description: "Creating schema and data relationships", status: "pending", progress: 0 },
  { id: "stage_05", name: "Backend Planning", description: "Defining API endpoints and service architecture", status: "pending", progress: 0 },
  { id: "stage_06", name: "Deployment Plan", description: "Generating infrastructure and deployment roadmap", status: "pending", progress: 0 },
];
